spring.jpa.hibernate.ddl-auto: none
spring.datasource:
    url: jdbc:mariadb://localhost:3306/portfolio
    username: portfolio
    password: senhaPortfolio
    driver-class-name: org.mariadb.jdbc.Driver


#Flyway properties
spring.flyway:
    enabled: true
    schemas: portfolio
    locations: classpath:db/migration/portfolio

spring.graphql:
    graphiql.enabled: true
    cors:
      allowed-origins: '*'