apiVersion: v1
kind: Secret
metadata:
  namespace: portfolio
  name: mariadb-root-secret
  labels:
    app: portfolio
    tier: database
type: Opaque
stringData:
  username: root
  password: birdsarentreal