apiVersion: v1
kind: Secret
metadata:
  namespace: portfolio
  name: mariadb-user-secret
  labels:
    app: portfolio
    tier: database
type: Opaque
stringData:
  username: portfolio
  password: senhaPortfolio