apiVersion: v1
kind: Service
metadata:
  namespace: portfolio
  name: mariadb
  labels:
    app: portfolio
    tier: database
spec:
  selector:
    app: portfolio
    tier: database
  ports:
    - protocol: TCP
      port: 3306